### ISSUE TITLE
resizing window messes some edges up

### ISSUE THREAD

**Issue by ofZach** [jacres/of-DeferredRendering#4]
if you change the window while this is running, you start to see the edges appear -- maybe the window and height of the screen are being cached somewhere and need to be updated?

![Screen Shot 2013-01-21 at 11 45 21 AM](https://f.cloud.github.com/assets/142897/83661/ffab48bc-63e9-11e2-89e6-a608bae5e577.png)

**Comment by jacres** [comment]
Hey Zach - I was trying to turn a blind eye to this issue ;) The way to solve it is to regenerate all the FBO textures to the new window size as it's resized. Shouldn't be too big of a deal to do. I'd love to make this example more OF-centric versus a lot of the OpenGL calls. I had to go with the OpenGL calls due to a few things with how ofTexture and ofFbo works. Maybe we can get a little discussion going on the dev list about some small tweaks that would make them a bit more flexible for certain cases - I'd love to help!

**Comment by jacres** [comment]
Should be fixed now - all the textures/buffers are recreated when the window size changes. Seems to work well, but let me know if you have any problems
